color0 #222f2f
color1 #fd4663
color2 #8bc1c1
color3 #8199b1
color4 #8585ad
color5 #acd3d3
color6 #afbfd0
color7 #f2f3f3
color8 #5e6e6d
color9 #fd4663
color10 #8bc1c1
color11 #8199b1
color12 #8585ad
color13 #acd3d3
color14 #afbfd0
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #000000
background            #000000
foreground            #f2f3f3
selection_foreground  #afb6b6
selection_background  #222f2f
active_border_color   #8bc1c1
inactive_border_color #071414
url_color             #8bc1c1

active_tab_foreground   #1b2222
active_tab_background   #8bc1c1
inactive_tab_foreground #afb6b6
inactive_tab_background #071414
cursor_trail_color      #afb6b6
