#default
##[main]
##include=~/.config/fuzzel/sapphire.ini
##font=Sans:size=14
# width=40
# lines=20
#
# ~/.config/fuzzel/fuzzel.ini

[main]
font=Sans:size=20
prompt=""
width=30
lines=5
horizontal-pad=20
vertical-pad=12
inner-pad=10
layer=overlay

[colors]
background=fffffff9
text=ffffff
match=8ab4f8ff
selection=ffffff22
selection-text=ffffff

[border]
width=0
radius=12
