general {
    hide_cursor = true
    grace = 2
}

background {
    monitor =
    path = ~/wallpapers/a.jpg

    blur_passes = 3
    blur_size = 6
    noise = 0.02
    contrast = 0.9
    brightness = 0.7
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date '+%H:%M')"
    color = rgba(ffffffff)
    font_size = 64
    font_family = JetBrains Mono
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] echo "$(date '+%A, %B %d')"
    color = rgba(ffffffaa)
    font_size = 16
    font_family = JetBrains Mono
    position = 0, 35
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 48
    position = 0, -40
    halign = center
    valign = center

    inner_color = rgba(00000055)
    outer_color = rgba(ffffff25)
    outline_thickness = 1

    font_color = rgb(ffffff)
    placeholder_text = 󰌾  Password
    check_color = rgba(ffffffcc)
    fail_color = rgba(ff5555cc)

    fade_on_empty = false
}

